# Python para Data Science: Introdução à linguagem e Numpy - parte 2

In [4]:
import numpy as np

In [9]:
from numpy import arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
km = np.array([1000, 2300, 4985, 1400, 6482])
km


array([1000, 2300, 4985, 1400, 6482])

In [13]:
type(km)

numpy.ndarray

In [14]:
km.dtype

dtype('int32')

In [16]:
km = np.loadtxt(fname = 'carros-km.txt', dtype = int)

km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [17]:
km.dtype

dtype('int32')

In [18]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [20]:
Acessorios = np.array(dados) 

Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [21]:
# 258 linhas
km.shape

(258,)

In [22]:
# 3 linhas  e 8  colunas
Acessorios.shape

(3, 8)

In [23]:
np_array = np.arange(10000000)

In [24]:
py_list = list(range(10000000))

In [26]:
# Ver desempenho da linha de codigo que esta sendo execultada
%time for _ in range (100): np_array *= 2


CPU times: total: 641 ms
Wall time: 684 ms


In [29]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: total: 1min 38s
Wall time: 1min 42s


In [30]:
# Calculo idade com Numpy
km = np.array([44410, 5712, 37123, 0, 25757])
anos = np.array([2003, 1991, 1990, 2019, 2006])


In [31]:
idade = 2019 - anos
idade

array([16, 28, 29,  0, 13])

In [33]:
#Operações entre array
km_media = km / idade
km_media

C:\Users\aline\AppData\Local\Temp\ipykernel_6844\998762443.py:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = km / idade


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [34]:
#Operações com array de duas dimensões 

dados = np.array([km, anos])
dados

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [36]:
dados.shape


(2, 5)

In [38]:
dados[0] [0]

44410

In [41]:
km_media = dados[0] / (2019 - dados[1])
km_media

C:\Users\aline\AppData\Local\Temp\ipykernel_6844\4063055428.py:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = dados[0] / (2019 - dados[1])


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [42]:
#Seleções com arrays

contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
#mostrar item especifico, seleciona o 6 pra mostrar o 5

item = 6
index = item -1
contador[index]

5

In [46]:
contador [-1]

9

In [47]:
dados[0]

array([44410,  5712, 37123,     0, 25757])

In [48]:
dados[1]

array([2003, 1991, 1990, 2019, 2006])

In [49]:
dados[1][2]

1990

In [50]:
dados[1, 2]

1990

In [51]:
#Fatiamento i: onde inicia  j:ponto de parada k: passo

contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
contador[1:4]

array([1, 2, 3])

In [53]:
contador[1:8:2]

array([1, 3, 5, 7])

In [55]:
#Varrendo toda a array de dois em dois
contador[::2]

array([0, 2, 4, 6, 8])

In [54]:
dados[:, 1:3]

array([[ 5712, 37123],
       [ 1991,  1990]])

In [56]:
dados[:, 1:3] [0]

array([ 5712, 37123])

In [57]:
dados[0]/ (2019 - dados[1])

C:\Users\aline\AppData\Local\Temp\ipykernel_6844\2079376839.py:1: RuntimeWarning: invalid value encountered in true_divide
  dados[0]/ (2019 - dados[1])


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [59]:
contador = np.arange(20)
contador

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [61]:
contador[contador > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
dados

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [63]:
dados [1] > 2000

array([ True, False, False,  True,  True])

In [64]:
dados [:, dados[1] > 2000]

array([[44410,     0, 25757],
       [ 2003,  2019,  2006]])

In [65]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteiro', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casado', 'feminino']
    ]
)

In [66]:
dados[0::2, :2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

In [75]:
dados = np.array([[44410, 5712, 37123, 0, 25757] ,
                [2003, 1991, 1990, 2019, 2006]])

dados                

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [76]:
# 2 linhas 5 colunas
dados.shape

(2, 5)

In [77]:
# Array com duas dimensões
dados.ndim

2

In [78]:
#Numero de elementos 
dados.size

10

In [79]:
# Rtorna o tipi dos elementos do array
dados.dtype

dtype('int32')

In [80]:
#Transforma  o array de linha para coluna e vice versa

dados.T

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

In [82]:
#Transforma  o array de linha para coluna e vice versa
dados.transpose()

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

In [87]:
# transforma o array  em uma lista 
dados.tolist()

[[44410, 5712, 37123, 0, 25757], [2003, 1991, 1990, 2019, 2006]]

In [112]:
contador = np.arange(10)
contador


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
#Retorna um array com os mesmo dados em uma nova forma
contador.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [115]:
#Retorna um array com os mesmo dados em uma nova forma Ordenada
contador.reshape((5, 2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [118]:
km = [44410, 5712, 37123, 0 , 25757]
anos = [2003, 19910, 1990, 2019, 2006]

In [122]:
#Concatenação

info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 19910, 1990, 2019, 2006]

In [123]:
np.array(info_carros).reshape((2, 5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003, 19910,  1990,  2019,  2006]])

In [125]:
np.array(info_carros).reshape((5, 2), order='F')

array([[44410,  2003],
       [ 5712, 19910],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

In [126]:
dados_new = dados.copy()
dados_new

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [129]:
dados_new.resize((3, 5), refcheck=False)
dados_new

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006],
       [    0,     0,     0,     0,     0]])

In [131]:
dados_new[2] = dados_new[0] / (2019 - dados_new[1])
dados_new

C:\Users\aline\AppData\Local\Temp\ipykernel_6844\3664879450.py:1: RuntimeWarning: invalid value encountered in true_divide
  dados_new[2] = dados_new[0] / (2019 - dados_new[1])


array([[      44410,        5712,       37123,           0,       25757],
       [       2003,        1991,        1990,        2019,        2006],
       [       2775,         204,        1280, -2147483648,        1981]])

In [132]:
anos = np.loadtxt(fname= "carros-anos.txt", dtype = int)
km = np.loadtxt (fname= "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [133]:
# array de uma dimesão com 258 linhas
anos.shape

(258,)

In [135]:
#Transforma arrays unidimensionais em um array bidimensionais
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [136]:
dataset.shape

(258, 3)

In [137]:
np.mean(dataset)

48489.14648578811

In [138]:
#media da kilometragem 
np.mean(dataset[:,1])

44499.41472868217

In [139]:
np.mean(dataset[:,2])

98960.51310077519

In [140]:
#desvio padrão
np.std(dataset[:,2])

29754.101150388564

In [141]:
#Somatorios, passa o eixo em que estar trabalhando
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [143]:
dataset[:, 1].sum()

11480849.0

In [144]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [145]:
np.sum(dataset[:, 2])

25531812.38